[package]
name = "twilight"
version = "0.0.0"
authors = ["Wang Xuerui <git@xen0n.name>"]
license = "Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
chrono = "0.4"

[dev-dependencies]
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
